controller_list:
  - name: fake_arm_controller
    joints:
      - joint_base
      - joint0
      - joint1
      - joint2
      - joint3
      - joint4
  - name: fake_gripper_controller
    joints:
      - joint5
      - joint6
      
